export const allsongs = [
    {
        "320kbps": "true",
        "album": "ANIMAL",
        "album_url": "https://www.jiosaavn.com/album/animal/8Ps4qqBA6,Y_",
        "albumid": "49986024",
        "artistMap": {
            "Raj Shekhar": "671644",
            "Vishal Mishra": "702452"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2023 Super Cassettes Industries Private Limited",
        "duration": "250",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8aRKCsl9a68YiLsvCnuTgb6h3UsgLa/i0s4PiTUymzaskESH3SPOM5o92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FhT4ZofmBRqbaEiVD7OpCbJoqtNYZYmUWMqMK+mjPbuwA4xL02OfPN9",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyxinPKFDOONH/Et1cshd2AW1YovHZ/6DmCPFQJZHjAJNdM2cswzHLvRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "1e0En7YX",
        "image": "https://c.saavncdn.com/092/ANIMAL-Hindi-2023-20231124191036-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "Pehle bhi main tumse mila hun",
        "media_preview_url": "https://preview.saavncdn.com/092/b3acb226721d5e51e788e9838f0261c3_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/092/b3acb226721d5e51e788e9838f0261c3_320.mp4",
        "music": "Vishal Mishra",
        "music_id": "702452",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/pehle-bhi-main/QQ1bdBoHbms",
        "play_count": 27384870,
        "primary_artists": "Vishal Mishra, Raj Shekhar",
        "primary_artists_id": "702452, 671644",
        "release_date": "2023-11-24",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Vishal Mishra, Raj Shekhar",
        "song": "Pehle Bhi Main",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910092152247",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910092108907.mp3",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Mere Ghar Ram Aaye Hain",
        "album_url": "https://www.jiosaavn.com/album/mere-ghar-ram-aaye-hain/dsife5uVB1k_",
        "albumid": "39209161",
        "artistMap": {
            "Jubin Nautiyal": "881158",
            "Manoj Muntashir": "473441",
            "Payal Dev": "653208"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2022 Super Cassettes Industries Private Limited",
        "duration": "234",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8TYk9lTFumEHFmL84wY54vmdixMrNAuxXj3Yg3JmcICIV2wDscmV3f492mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FjJuhrj+FJtuKPCw8Kor3ayiokJWCn4qWgdcA2+WIxz7IRhZHrOUj/b",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyEs7nXKoT669b3hO1CR26pZ40TvOn/CswcBC83eH8qHylYR86Ia32Lhw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "q3ElTqvW",
        "image": "https://c.saavncdn.com/946/Mere-Ghar-Ram-Aaye-Hain-Hindi-2022-20221019191009-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "bajaao dhol swaagat mein, mere ghar ram aaye hain",
        "media_preview_url": "https://preview.saavncdn.com/946/9639eff1be049ac7f92683fc44dc9131_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/946/9639eff1be049ac7f92683fc44dc9131_320.mp4",
        "music": "Payal Dev",
        "music_id": "653208",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/mere-ghar-ram-aaye-hain/AVsuXSBBQWQ",
        "play_count": 44002028,
        "primary_artists": "Jubin Nautiyal, Payal Dev, Manoj Muntashir",
        "primary_artists_id": "881158, 653208, 473441",
        "release_date": "2022-10-20",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Jubin Nautiyal, Payal Dev, Manoj Muntashir",
        "song": "Mere Ghar Ram Aaye Hain",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910091894701",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091851192.mp3",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Bhediya",
        "album_url": "https://www.jiosaavn.com/album/bhediya/wSM2AOubajk_",
        "albumid": "38682222",
        "artistMap": {
            "Amitabh Bhattacharya": "458681",
            "Arijit Singh": "459320",
            "Kriti Sanon": "701752",
            "Sachin-Jigar": "461968",
            "Varun Dhawan": "511656"
        },
        "cache_state": "false",
        "copyright_text": "© 2023 Zee Music Company",
        "duration": "261",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8CfY1zdgLGXS2HtjPLyiS6s4ZMW+JiKwS5R2I8PfKxpApEucsNRL/tY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FjXKc7wt918H5XSRhBMYlCAspIqZBRbH3w1K4QAICdSFxaEUxAFcUhY",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDylA8lQwDowJF0rwulZQb41oGFWui//Ii/9d8Rp0MdqrAGAnyTSi1MVxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "qZtKBMZ_",
        "image": "https://c.saavncdn.com/815/Bhediya-Hindi-2023-20230927155213-500x500.jpg",
        "is_dolby_content": false,
        "label": "Zee Music Co.",
        "label_url": "/label/zee-music-co.-albums/06cepoPTlhU_",
        "language": "hindi",
        "lyrics_snippet": "Jag Ki Hirasat Se",
        "media_preview_url": "https://preview.saavncdn.com/815/483a6e118e8108cbb3e5cd8701674f32_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/815/483a6e118e8108cbb3e5cd8701674f32_320.mp4",
        "music": "Sachin-Jigar",
        "music_id": "461968",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/apna-bana-le/ATIfejZ9bWw",
        "play_count": 129222015,
        "primary_artists": "Sachin-Jigar, Arijit Singh",
        "primary_artists_id": "461968, 459320",
        "release_date": "2023-09-27",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Sachin-Jigar, Arijit Singh",
        "song": "Apna Bana Le",
        "starred": "false",
        "starring": "Varun Dhawan, Kriti Sanon",
        "triller_available": false,
        "type": "",
        "vcode": "010910441729728",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910441686043.mp3",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Guntur Kaaram",
        "album_url": "https://www.jiosaavn.com/album/guntur-kaaram/d28KxzEcK-Q_",
        "albumid": "49567583",
        "artistMap": {
            "Mahesh Babu": "461646",
            "Meenakshii Chaudhary": "11455690",
            "Ramajogayya Sastry": "455178",
            "Sahithi Chaganti": "1846675",
            "Sreeleela": "11731368",
            "Sri Krishna": "457304",
            "Thaman S": "544471"
        },
        "cache_state": "false",
        "copyright_text": "© 2023 Aditya Music",
        "duration": "216",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8/ROFheR9Qm7/x5b+Hpkpzktvq75jNxCVegpI8PH2zSWTlJgYgTQcfY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FiWOPpG5+Bkd0osuFdHoaB6C5mrt4nd0pnkwiqMTrISizTp4PCfWZmB",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyAYSpkEihdkG4+AFn1gYNkJM9bhyDhDoC00is5zg9wSEUPgFYtzlXCxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "ARuXdxyk",
        "image": "https://c.saavncdn.com/000/Guntur-Kaaram-Telugu-2023-20240126145901-500x500.jpg",
        "is_dolby_content": false,
        "label": "Aditya Music",
        "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
        "language": "telugu",
        "lyrics_snippet": "Aa Kurchini Madatha Petti",
        "media_preview_url": "https://preview.saavncdn.com/000/a8b06cdf02fd61001823e10d55ad3ebe_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/000/a8b06cdf02fd61001823e10d55ad3ebe_320.mp4",
        "music": "Thaman S",
        "music_id": "544471",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/kurchi-madathapetti/MToeaRBITlg",
        "play_count": 6615558,
        "primary_artists": "Mahesh Babu, Thaman S, Sri Krishna, Sahithi Chaganti",
        "primary_artists_id": "461646, 544471, 457304, 1846675",
        "release_date": "2023-11-07",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Thaman S, Sri Krishna, Sahithi Chaganti, Mahesh Babu",
        "song": "Kurchi Madathapetti",
        "starred": "false",
        "starring": "Mahesh Babu, Sreeleela, Meenakshii Chaudhary",
        "triller_available": false,
        "type": "",
        "vcode": "010910402193409",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910402149524.mp3",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Heeriye (feat. Arijit Singh)",
        "album_url": "https://www.jiosaavn.com/album/heeriye-feat.-arijit-singh/ESDOfVN2cxY_",
        "albumid": "45664234",
        "artistMap": {
            "Arijit Singh": "459320",
            "Dulquer Salmaan": "823817",
            "Jasleen Royal": "742789"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2023 Meri Marzi Pictures LLP under exclusive license to Warner Music India",
        "duration": "194",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8tq5Ac1TyBCA5OHEnKQSwAgzhQEo43rxmN9KMYFP+AXJSHsyZ7dekbo92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FhqkTw/kTlpf5V0yuWvjIRJtWSSA6+w1Z+3cEKUrSEdJtaNpKR9zlit",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy3vhmFtOjRtXY2Jd9diqBZ8kwqCoUZVMfOlB2hzeQTstaNX0TDV46RRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "NIidiD9g",
        "image": "https://c.saavncdn.com/022/Heeriye-feat-Arijit-Singh-Hindi-2023-20230928050405-500x500.jpg",
        "is_dolby_content": false,
        "label": "Warner Music India",
        "label_url": "/label/warner-music-india-albums/4j6ISMnao78_",
        "language": "hindi",
        "lyrics_snippet": "Heeriye heeriye aa",
        "media_preview_url": "https://preview.saavncdn.com/022/a192e8d320ea5630db314d04fedf0aa5_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/022/a192e8d320ea5630db314d04fedf0aa5_320.mp4",
        "music": "Jasleen Royal, Arijit Singh, Dulquer Salmaan",
        "music_id": "742789, 459320, 823817",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/heeriye-feat.-arijit-singh/PiECVR10DlQ",
        "play_count": 47608107,
        "primary_artists": "Dulquer Salmaan, Jasleen Royal, Arijit Singh",
        "primary_artists_id": "823817, 742789, 459320",
        "release_date": "2023-07-25",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "",
        "song": "Heeriye (feat. Arijit Singh)",
        "starred": "false",
        "starring": "Dulquer Salmaan, Jasleen Royal",
        "triller_available": false,
        "type": "",
        "vcode": "010912552046639",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010912552003505.mp3",
        "webp": true,
        "year": "2023"
    },    {
        "320kbps": "true",
        "album": "Relaxing Music",
        "album_url": "https://www.jiosaavn.com/album/relaxing-music/YD9ZM1IzLj4_",
        "albumid": "1256524",
        "artistMap": {
            "Relaxing Music": "849700"
        },
        "cache_state": "false",
        "copyright_text": "© 2011 Autumn Hill Records",
        "duration": "128",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8AQkDWRl3U7RCl93en+qQYuXBFSG4SSqVEyGFKeLjZeYQAuU+Oo6FlY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FgXGMqD8jDG5D42RMh/Ys7sQWF6D7+MwONodj7L8JIS7oniYUnV36AR",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyQKnZEKtX+y/OiHtJG/oLpr/PKvkI/xDTN5t/KGlx607QXAwwNBNenxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "P5Hf-peS",
        "image": "https://c.saavncdn.com/426/Relaxing-Music-English-2011-500x500.jpg",
        "is_dolby_content": false,
        "label": "Autumn Hill Records",
        "label_url": "/label/autumn-hill-records-albums/gJ06W5wovCA_",
        "language": "english",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/426/912c1b00ae793a7983352e2522e1d6fe_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/426/912c1b00ae793a7983352e2522e1d6fe_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-music/IF0jV1lAUmA",
        "play_count": 517621,
        "primary_artists": "Relaxing Music",
        "primary_artists_id": "849700",
        "release_date": "2011-02-25",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Relaxing Music",
        "song": "Relaxing Music",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2011"
    },
    {
        "320kbps": "true",
        "album": "1 Hour Of Rain",
        "album_url": "https://www.jiosaavn.com/album/1-hour-of-rain/EflA48UR3xU_",
        "albumid": "16721916",
        "artistMap": {
            "Rain Sounds": "855365",
            "Rain for Deep Sleep": "1477756"
        },
        "cache_state": "false",
        "copyright_text": "© 2019 Rain Sounds",
        "duration": "120",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8+o7bphmcslwnqZn8Hkc5w302AgTfcw49/JNGLWdOa9T9Gwp1IvFpk492mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FhM/7fJk7C2PygA/rQdcXI9+Rr62gNHgcjFDiP6h2Cn3s0r4M6oqJJA",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyZmUWa3gw/hDcPBODHxVMLpMpxQwnznRmxEGIWEKWbT4Pd3+tVTwlnhw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "JDOgvPhy",
        "image": "https://c.saavncdn.com/391/1-Hour-Of-Rain-English-2019-20190725115328-500x500.jpg",
        "is_dolby_content": false,
        "label": "BodyHI",
        "label_url": "/label/bodyhi-albums/9M65-fGAs-k_",
        "language": "english",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/391/4d0616e49257ce5365ff2e4a7d7ba571_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/391/4d0616e49257ce5365ff2e4a7d7ba571_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-light-raindrops/OiwkVgJgX0o",
        "play_count": 64498,
        "primary_artists": "Rain For Deep Sleep, Rain Sounds",
        "primary_artists_id": "1477756, 855365",
        "release_date": "2019-08-05",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Rain For Deep Sleep, Rain Sounds",
        "song": "Relaxing Light Raindrops",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2019"
    },
    {
        "320kbps": "true",
        "album": "Sleeping Music For Sleep, Relaxation and Binaural Beats Sleep Music",
        "album_url": "https://www.jiosaavn.com/album/sleeping-music-for-sleep-relaxation-and-binaural-beats-sleep-music/SdJN,HrUQco_",
        "albumid": "13013352",
        "artistMap": {
            "Deep Sleep Music Collective": "3164399",
            "Sleeping Music": "850897",
            "Sleeping Music Experience": "3426299"
        },
        "cache_state": "false",
        "copyright_text": "© 2018 Sleeping Music Experience",
        "duration": "140",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8zf/N1HeeU9z+Ie1oHw+8D9H7ZR/o+CQ3vOHljQY24fzqqudd+d0zKY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FiDBAryNndJQ0XCAwD/7ROv0TxFQA29Xq0kwX9juoMxGvyF+RAsee98",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyPHkk5ergEJsRtl4mGfo1ANmY92WQZzdLIfSKRaX9Iy6jbbmNKH3DWRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "T9CHIm7V",
        "image": "https://c.saavncdn.com/820/Sleeping-Music-For-Sleep-Relaxation-and-Binaural-Beats-Sleep-Music-English-2018-20180529162735-500x500.jpg",
        "is_dolby_content": false,
        "label": "Fireheart Music, Inc",
        "label_url": "/label/fireheart-music-inc-albums/RpnRGhZKcD0_",
        "language": "english",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/820/4a8155563c8153ae4035353ac0012bdd_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/820/4a8155563c8153ae4035353ac0012bdd_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-music-for-sleep/JFEoeT1dAGU",
        "play_count": 42054,
        "primary_artists": "Sleeping Music Experience, Deep Sleep Music Collective, Sleeping Music",
        "primary_artists_id": "3426299, 3164399, 850897",
        "release_date": "2018-05-05",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Sleeping Music Experience, Deep Sleep Music Collective, Sleeping Music",
        "song": "Relaxing Music For Sleep",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2018"
    },
    {
        "320kbps": "true",
        "album": "Study Music: Calm Music for Studying, Reading Music, Concentration and Focus and Relaxing Studying Music",
        "album_url": "https://www.jiosaavn.com/album/study-music-calm-music-for-studying-reading-music-concentration-and-focus-and-relaxing-studying-music/yfIi41C3NFA_",
        "albumid": "11403365",
        "artistMap": {
            "Study Music": "849623"
        },
        "cache_state": "false",
        "copyright_text": "©  2017 Study Music",
        "duration": "132",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8ms8M9PiQdlOp9zLEuTZOvaMF6xVQTO++bkWdm9uAgM5yjP/z1hTLjo92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FgNoiBSsn0iEmlWuvrrkgcIAO4NEsZ8NkOjdwj0CaL26IzzYlFDMEkp",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy+licucfwgrHvZ6jA6emmpUSiZW8pLN1h9VUMEmjz1dDlgM0eru+jahw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "YXSkivdv",
        "image": "https://c.saavncdn.com/262/Study-Music-Calm-Music-for-Studying-Reading-Music-Concentration-and-Focus-and-Relaxing-Studying-Music-English-2017-20170912190712-500x500.jpg",
        "is_dolby_content": false,
        "label": "Study Music",
        "label_url": "/label/study-music-albums/np6zGEQO5tg_",
        "language": "english",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/262/47647f92028ca1d119616849daa8755e_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/262/47647f92028ca1d119616849daa8755e_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-study-music-for-tests/KTA4Wh1GU0U",
        "play_count": 90469,
        "primary_artists": "Study Music",
        "primary_artists_id": "849623",
        "release_date": "2017-08-23",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Study Music",
        "song": "Relaxing Study Music for Tests",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": false,
        "year": "2017"
    },
    {
        "320kbps": "true",
        "album": "Sleeping Music: Calm Music For Sleep, Deep Sleep Aid and Relaxing Flute Music",
        "album_url": "https://www.jiosaavn.com/album/sleeping-music-calm-music-for-sleep-deep-sleep-aid-and-relaxing-flute-music/V2zV6zzJAaw_",
        "albumid": "14821581",
        "artistMap": {
            "Deep Sleep Music Collective": "3164399",
            "Sleeping Music": "850897",
            "Sleeping Music Experience": "3426299"
        },
        "cache_state": "false",
        "copyright_text": "© 2019 Sleeping Music",
        "duration": "117",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8I0IMUcoY89lD8jc5Xx1rX3NuDpo2lZKZFhc4TN85tUkpEpm2mu1D5I92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/Fihhnmz/asYkSvvvaQXjPzVoZk+Fm85n/Nb+4UvRuGfugVhH9YO3sJM",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyGTub/PiojZoLER6pNEOT/sQcQfD3vz9J5TG8TxeeZ3jP7UOdjF9ulhw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "VnEFd6Fl",
        "image": "https://c.saavncdn.com/338/Sleeping-Music-Calm-Music-For-Sleep-Deep-Sleep-Aid-and-Relaxing-Flute-Music-English-2019-20190109042915-500x500.jpg",
        "is_dolby_content": false,
        "label": "Fireheart Music, Inc",
        "label_url": "/label/fireheart-music-inc-albums/RpnRGhZKcD0_",
        "language": "english",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/338/c722ac55f5254e04b881ca4ab756ca19_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/338/c722ac55f5254e04b881ca4ab756ca19_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-flute-music/JgYudxAGcV8",
        "play_count": 39541,
        "primary_artists": "Sleeping Music Experience, Deep Sleep Music Collective, Sleeping Music",
        "primary_artists_id": "3426299, 3164399, 850897",
        "release_date": "2019-01-09",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Sleeping Music Experience, Deep Sleep Music Collective, Sleeping Music",
        "song": "Relaxing Flute  Music",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2019"
    },{
        "320kbps": "true",
        "album": "Maari",
        "album_url": "https://www.jiosaavn.com/album/maari/sdjpUZo9-HI_",
        "albumid": "1251943",
        "artistMap": {
            "Alisha Thomas": "852328",
            "Anirudh Ravichander": "455663",
            "Dhanush": "455662",
            "Kajal Aggarwal": "479962",
            "Vijay Yesudas": "455508"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2015 Sony Music Entertainment India Pvt. Ltd.",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "198",
        "encrypted_media_path": "NMKyboFo/FjfeSkxFSPJUsYtD6UY61S6l8o29Djc5L6pyxdq2GwY6LQdPiXVE/pY",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDymj8i23FAu9Rv/Xw82Gvq9OTyBAYGlIq7xcxCApLEb/mZCahnuDnmfBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "eUgNtCfF",
        "image": "https://c.saavncdn.com/098/Maari-Tamil-2015-20200806144615-500x500.jpg",
        "is_dolby_content": false,
        "label": "Sony Music Entertainment India Pvt. Ltd.",
        "label_url": "/label/sony-music-entertainment-india-pvt.-ltd.-albums/LaFAA6h1q2U_",
        "language": "tamil",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/098/b78c21845f8c057dde7375d09714da85_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/098/b78c21845f8c057dde7375d09714da85_320.mp4",
        "music": "Anirudh Ravichander",
        "music_id": "455663",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/donu-donu-donu-the-dons-romance/FT0MfwBzUXU",
        "play_count": 25380940,
        "primary_artists": "Anirudh Ravichander, Alisha Thomas",
        "primary_artists_id": "455663, 852328",
        "release_date": "2015-06-07",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Anirudh Ravichander, Alisha Thomas",
        "song": "Don'u Don'u Don'u (The Don's Romance)",
        "starred": "false",
        "starring": "Dhanush, Kajal Aggarwal, Vijay Yesudas",
        "triller_available": false,
        "type": "",
        "vcode": "010910140014009",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910140016787.mp3",
        "webp": true,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Romance Like SRK - Mashup",
        "album_url": "https://www.jiosaavn.com/album/romance-like-srk-mashup/9QAzzd4SXlk_",
        "albumid": "1224192",
        "artistMap": {
            "A.R. Rahman": "456269",
            "Anand Bakshi": "456000",
            "Gulzar": "455704",
            "Jaideep Sahni": "464645",
            "Javed Akhtar": "455447",
            "Lata Mangeshkar": "455109",
            "Madan Mohan": "455994",
            "Mohit Chauhan": "455124",
            "Roopkumar Rathod": "455459",
            "Salim-Sulaiman": "456102",
            "Shreya Ghoshal": "455130",
            "Sonu Nigam": "455125",
            "Sunny Subramanian": "615445",
            "Udit Narayan": "455127",
            "Uttam Singh": "461323"
        },
        "cache_state": "false",
        "copyright_text": "©  2015 YRF Music",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "206",
        "encrypted_media_path": "NMKyboFo/FifJvv2QnVM5zjL9lVsosxTSW7jgynTKFcFKs6y5jOu53Oz/l3Ws1wN",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyXYHVQGxLNeIzpUi5RmwWwS5sUFn96Gff71w0osXDvROTbKhZfUHv0Bw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "_ovxilTH",
        "image": "https://c.saavncdn.com/209/Romance-Like-SRK-Mashup-Hindi-2015-500x500.jpg",
        "is_dolby_content": false,
        "label": "YRF Music",
        "label_url": "/label/yrf-music-albums/XqFShgT4cps_",
        "language": "hindi",
        "lyrics_snippet": "main yahaan, hoon  yahaan, hoon  yahaan, hoon  yahaan",
        "media_preview_url": "https://preview.saavncdn.com/209/767f0d507529636a9711f612fb1d6ba3_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/209/767f0d507529636a9711f612fb1d6ba3_320.mp4",
        "music": "Salim-Sulaiman, Madan Mohan, A.R. Rahman, Uttam Singh",
        "music_id": "456102, 455994, 456269, 461323",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-like-srk-mashup/LwcdSR1cY3s",
        "play_count": 2446808,
        "primary_artists": "Sunny Subramanian, Roopkumar Rathod, Lata Mangeshkar, Sonu Nigam, Shreya Ghoshal, Mohit Chauhan, Udit Narayan",
        "primary_artists_id": "615445, 455459, 455109, 455125, 455130, 455124, 455127",
        "release_date": "2015-02-13",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Sunny Subramanian, Roopkumar Rathod, Lata Mangeshkar, Sonu Nigam, Shreya Ghoshal, Mohit Chauhan, Udit Narayan",
        "song": "Romance Like SRK - Mashup",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": false,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Shuddh Desi Romance",
        "album_url": "https://www.jiosaavn.com/album/shuddh-desi-romance/iM48O83xLxk_",
        "albumid": "1142649",
        "artistMap": {
            "Benny Dayal": "456521",
            "Jaideep Sahni": "464645",
            "Parineeti Chopra": "473372",
            "Rishi Kapoor": "455081",
            "Sachin-Jigar": "461968",
            "Shalmali": "467027",
            "Sushant Singh Rajput": "2180329",
            "Vaani Kapoor": "673052"
        },
        "cache_state": "false",
        "copyright_text": "©  2013 Yash Raj Films",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "186",
        "encrypted_media_path": "NMKyboFo/FglVjPcNcvYPBhBlR5rkvjXOXAYcz3M2TMQz33vqCZRfT5E8qqovwkI",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDypqD+WumPaC4qJE6wAvXvMHE+Ls82WbkgdOuTdY70FELYVpfbWeuBoxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "g86S97py",
        "image": "https://c.saavncdn.com/152/Shuddh-Desi-Romance-Hindi-2013-20190329150640-500x500.jpg",
        "is_dolby_content": false,
        "label": "Yash Raj Films",
        "label_url": "/label/yash-raj-films-albums/A3Yzr-GkEGE_",
        "language": "hindi",
        "lyrics_snippet": "शुद्ध देसी, देसी-देसी romance (कमीने, हाए, रे)",
        "media_preview_url": "https://preview.saavncdn.com/152/1866eb5742fcb88375d0573e754d6992_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/152/1866eb5742fcb88375d0573e754d6992_320.mp4",
        "music": "Sachin-Jigar",
        "music_id": "461968",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/shuddh-desi-romance/F1BdYk0HR0o",
        "play_count": 3188035,
        "primary_artists": "Sachin-Jigar, Benny Dayal, Shalmali",
        "primary_artists_id": "461968, 456521, 467027",
        "release_date": "2013-07-23",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Benny Dayal, Shalmali",
        "song": "Shuddh Desi Romance",
        "starred": "false",
        "starring": "Sushant Singh Rajput, Parineeti Chopra, Vaani Kapoor, Rishi Kapoor",
        "triller_available": false,
        "type": "",
        "vcode": "010910391621687",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910391577526.mp3",
        "webp": true,
        "year": "2013"
    },
    {
        "320kbps": "true",
        "album": "Tholi Prema",
        "album_url": "https://www.jiosaavn.com/album/tholi-prema/KbDktRPOXbI_",
        "albumid": "1219030",
        "artistMap": {
            "Ali": "460923",
            "Bhuvana Chandra": "455678",
            "Deva": "455219",
            "Keerthi Reddy": "462761",
            "P. Unnikrishnan": "586086",
            "Pawan Kalyan": "461297",
            "Suresh Peters": "460765"
        },
        "cache_state": "false",
        "copyright_text": "©  1998 YBR Music Publishing Pvt Ltd",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "287",
        "encrypted_media_path": "NMKyboFo/FgyUf0Z1wTgdwGL6BaCv2yz90ugecLfNW61V4P7bSMlbFsu5qgmnC96",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyhsg51fV0GlDbFXeyUdikITULixAi/AfNXJw9U7j/3F6It2DJoSxxixw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "8z3ukHsL",
        "image": "https://c.saavncdn.com/498/Tholi-Prema-Telugu-1998-500x500.jpg",
        "is_dolby_content": false,
        "label": "YBR Music Publishing Pvt Ltd",
        "label_url": "/label/ybr-music-publishing-pvt-ltd-albums/8vIYXCFLeKY_",
        "language": "telugu",
        "lyrics_snippet": "Romance Lo Rhythms Kalagalipina",
        "media_preview_url": "https://preview.saavncdn.com/498/6110cf4fad5e1ca97b59993cdaa8e83c_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/498/6110cf4fad5e1ca97b59993cdaa8e83c_320.mp4",
        "music": "Deva",
        "music_id": "455219",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-rythms/SBJYRB94RH8",
        "play_count": 969767,
        "primary_artists": "Deva, Suresh Peters, P. Unnikrishnan",
        "primary_artists_id": "455219, 460765, 586086",
        "release_date": "1998-07-24",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Suresh Peters, P. Unnikrishnan",
        "song": "Romance Rythms",
        "starred": "false",
        "starring": "Pawan Kalyan, Keerthi Reddy, Ali",
        "triller_available": false,
        "type": "",
        "vcode": "010910090839368",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910090795820.mp3",
        "webp": false,
        "year": "1998"
    },
    {
        "320kbps": "true",
        "album": "Jaan Tere Naam",
        "album_url": "https://www.jiosaavn.com/album/jaan-tere-naam/UakrIFtuSYA_",
        "albumid": "43200392",
        "artistMap": {
            "Farheen": "733182",
            "Kumar Sanu": "455142",
            "Nadeem-Shravan": "456307",
            "Ronit Roy": "455319",
            "Surendra Saathi": "476826"
        },
        "cache_state": "false",
        "copyright_text": "© 1992 Tips Industries Ltd.",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "413",
        "encrypted_media_path": "NMKyboFo/FgIgQ6WJleYKdoS5qFP9V+bEg9bPTkdnbwPbmkf6uJzvr6R1FViaR0b",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy35RwF1LTxgguW7+bICN+REVFU9GhM+2RlQ0Bt4IdrROFl44p7o6Lbxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "2AYT4UsD",
        "image": "https://c.saavncdn.com/172/Jaan-Tere-Naam-Hindi-1992-20230304140459-500x500.jpg",
        "is_dolby_content": false,
        "label": "Tips Industries Ltd.",
        "label_url": "/label/tips-industries-ltd.-albums/,1uKiglGzEk_",
        "language": "hindi",
        "lyrics_snippet": "Mana ki college main perna chaiye like na chaiye.",
        "media_preview_url": "https://preview.saavncdn.com/172/ff32ded6f5ccc4d8911b0ea570d0189a_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/172/ff32ded6f5ccc4d8911b0ea570d0189a_320.mp4",
        "music": "Kumar Sanu, Nadeem-Shravan",
        "music_id": "455142, 456307",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-period/QikyZUBlRHc",
        "play_count": 604431,
        "primary_artists": "Kumar Sanu",
        "primary_artists_id": "455142",
        "release_date": "1992-02-21",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "",
        "song": "Romance Period",
        "starred": "false",
        "starring": "Ronit Roy, Farheen",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "1992"
    },{
        "320kbps": "true",
        "album": "Sajna-Lofi",
        "album_url": "https://www.jiosaavn.com/album/sajna-lofi/tHacN1TFLmY_",
        "albumid": "37096195",
        "artistMap": {
            "Arijit Singh": "459320",
            "Arindom": "1312196",
            "Prasen": "532403"
        },
        "cache_state": "false",
        "copyright_text": "© 2022 SVF Music",
        "duration": "188",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD81rDYq5k05Cb+FK4ItIOn3oeaG1iZ8zk/au1XjUHxLmBzcaTnXhd9BI92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/Fhb5abO5bYeBc49jf1WnEIyAQhml7+odpHMaEtPktW0wKbDxLzeX2AR",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyNGzozTPJ/32/AdU7YZqdhsGQyEGOlPrDRGub+eVk2xho/P0pUzF0VRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "k03tA-da",
        "image": "https://c.saavncdn.com/216/Sajna-Lofi-Bengali-2022-20220806060504-500x500.jpg",
        "is_dolby_content": false,
        "label": "Shree Venkatesh Films Pvt. Ltd.",
        "label_url": "/label/shree-venkatesh-films-pvt.-ltd.-albums/9ijex,8qafE_",
        "language": "bengali",
        "lyrics_snippet": "साजना, लागे ना अब अखियाँ तोरे बिन",
        "media_preview_url": "https://preview.saavncdn.com/216/12e6aa733fb9d1d4a5f11493fc65536b_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/216/12e6aa733fb9d1d4a5f11493fc65536b_320.mp4",
        "music": "Arindom",
        "music_id": "1312196",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/sajna-lofi/G1hYRTUdU1I",
        "play_count": 3352318,
        "primary_artists": "Arijit Singh",
        "primary_artists_id": "459320",
        "release_date": "2022-08-05",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Arijit Singh",
        "song": "Sajna-Lofi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910091647423",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091603746.mp3",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Romantic Lofi (Slowed & Reverb)",
        "album_url": "https://www.jiosaavn.com/album/romantic-lofi-slowed-reverb/5tQeeUFO-JU_",
        "albumid": "39090781",
        "artistMap": {
            "Manish Zay": "14353980"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2022 Manish Zay Music",
        "duration": "512",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD83xtDE/IFPD5btnIGgjCDyUOOMS92t0ZTY8ww3j+E9a/hQvlrxvJ1w492mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/Fix8b2IoZ2TMV6vra5eyQxohMO/92U+ZRzylnaog1CvvBxcszeoGszd",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDysgjPjHvqOCo3iv0MiHEWBQF1UpUi7pebPGGCWDZ8qjYYXtwzbK2q/hw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "0QnKJx4e",
        "image": "https://c.saavncdn.com/172/Romantic-Lofi-Slowed-Reverb-Hindi-2022-20221014234716-500x500.jpg",
        "is_dolby_content": false,
        "label": "Manish Zay Music",
        "label_url": "/label/manish-zay-music-albums/FeFiyK9ve30_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/172/330905dfa73d338765aa5f47c494c406_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/172/330905dfa73d338765aa5f47c494c406_320.mp4",
        "music": "Manish Zay",
        "music_id": "14353980",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romantic-lofi-slowed-reverb/QDkFej5IA1Y",
        "play_count": 861520,
        "primary_artists": "Manish Zay",
        "primary_artists_id": "14353980",
        "release_date": "2022-10-14",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "",
        "song": "Romantic Lofi (Slowed & Reverb)",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Tum Mile (Lofi Flip)",
        "album_url": "https://www.jiosaavn.com/album/tum-mile-lofi-flip/jpcTg9egglw_",
        "albumid": "28749361",
        "artistMap": {
            "KSW": "5119226",
            "Kumaar": "455665",
            "Neeraj Shridhar": "455694",
            "Neeraj Shridhar &amp; Pritam": "",
            "Pritam": "456323"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2021 Sony Music Entertainment India Pvt. Ltd.",
        "duration": "242",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8i7eqcY7KhMSNXGPLfUUxBxpXQKu8sjlROFY3Hy0Dc2L8AxGpHFoYIY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FgbjqbTa4jG41SxvH6mA1E2dDWQ6+mJQk5WBDfj+tAbBCU+Fc+YcDqT",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDycTrDC9yCtwqX597IFy6j1Z8pGLRLjbwksuXf9LI01wm81URfLbqTcBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "iGsrkt9W",
        "image": "https://c.saavncdn.com/259/Tum-Mile-Lofi-Flip--Hindi-2021-20210730210034-500x500.jpg",
        "is_dolby_content": false,
        "label": "Sony Music Entertainment India Pvt. Ltd.",
        "label_url": "/label/sony-music-entertainment-india-pvt.-ltd.-albums/LaFAA6h1q2U_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/259/1ee450f9addeccd7bb00e8ab19d9d3f4_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/259/1ee450f9addeccd7bb00e8ab19d9d3f4_320.mp4",
        "music": "Pritam",
        "music_id": "456323",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/tum-mile-lofi-flip/GS8YQx9EDmQ",
        "play_count": 12403811,
        "primary_artists": "KSW, Neeraj Shridhar, Pritam",
        "primary_artists_id": "5119226, 455694, 456323",
        "release_date": "2021-08-13",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "KSW, Neeraj Shridhar, Pritam, KSW, Neeraj Shridhar & Pritam",
        "song": "Tum Mile (Lofi Flip)",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910141422379",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910141378295.mp3",
        "webp": true,
        "year": "2021"
    },
    {
        "320kbps": "true",
        "album": "Detail LoFi",
        "album_url": "https://www.jiosaavn.com/album/detail-lofi/zpTp7W69vXg_",
        "albumid": "42179618",
        "artistMap": {
          "Deep Chambal": "8362992"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2023 Judge Records",
        "duration": "208",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8qdBO3WSXJ8iDhXBtNR0VIy/AeIRfMnM/elI5ptDQ0kfhQsnH/H4MM492mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FjSTyz3e2GLkhWVufbDkrHEDXGpvoO/P/LfIsQycw8i9/jqM+vw98iA",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDysB2CYtoAGmGroto6tnI1hN2+pL8xdjHqW4F1wY+MIpLh3nkKMC+/Uhw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "7WlE6SWB",
        "image": "https://c.saavncdn.com/702/Detail-LoFi-Punjabi-2023-20230131194626-500x500.jpg",
        "is_dolby_content": false,
        "is_drm": 1,
        "label": "Judge Records",
        "label_url": "/label/judge-records-albums/-pRGS5AL-iw_",
        "language": "punjabi",
        "lyrics_snippet": "tainu feem de boote waangu dekh chade lore",
        "media_preview_url": "https://preview.saavncdn.com/702/7806fb7fdb5c593695bb137108648533_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/702/7806fb7fdb5c593695bb137108648533_320.mp4",
        "music": "Deep Chambal",
        "music_id": "8362992",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/detail-lofi/Rz8HdEJjYHE",
        "play_count": 737118,
        "primary_artists": "Deep Chambal",
        "primary_artists_id": "8362992",
        "release_date": "2023-01-27",
        "rights": {
          "cacheable": true,
          "code": 0,
          "delete_cached_object": false,
          "reason": ""
        },
        "singers": "Deep Chambal",
        "song": "Detail LoFi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2023"
      },
      {
        "320kbps": "true",
    "album": "Sad Lofi Hits",
    "album_url": "https://www.jiosaavn.com/album/sad-lofi-hits/KzLzeRhY6H4_",
    "albumid": "38272905",
    "artistMap": {
      "Javed Akhtar": "455447",
      "Kishore Kumar": "455144",
      "Lata Mangeshkar": "455109",
      "Sachin Gupta": "461964",
      "Shiv-Hari": "466097"
    },
    "cache_state": "false",
    "copyright_text": "℗ 2022 Saregama India Ltd",
    "duration": "203",
    "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8UdLAqjfaZ/WhPt2S0058zQz4DRRD9KiFnJvhib7l8rD9SPEZd20kAY8GeVWllz/R+eH/WfcUtpz13AyVsnfI3g==",
    "encrypted_media_path": "NMKyboFo/FjlVbAdOnEPvlc0t7Zw8ykjEPMWdnSjOz4I7EuFNyTV7PSu+vLquK9D",
    "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyMnHHe3dmhgp+ZNZ79cIzTpAH0AC3n49DhYuIzP8i6r0I0aOTB2rVJPhveXdhRkFeGBTsxqxbyf8=",
    "explicit_content": 0,
    "featured_artists": "",
    "featured_artists_id": "",
    "has_lyrics": "true",
    "id": "8_iRZkgo",
    "image": "https://c.saavncdn.com/311/Sad-Lofi-Hits-Hindi-2022-20220915113902-500x500.jpg",
    "is_dolby_content": false,
    "is_drm": 1,
    "label": "Saregama",
    "label_url": "/label/saregama-albums/MNccah3udrQ_",
    "language": "hindi",
    "lyrics_snippet": "dekha ek khwaab to ye silsile hue",
    "media_preview_url": "https://preview.saavncdn.com/311/553b82d6967eff2a3fa9c75ecc11244d_sar_96_p.mp4",
    "media_url": "https://aac.saavncdn.com/311/553b82d6967eff2a3fa9c75ecc11244d_sar_320.mp4",
    "music": "Kishore Kumar, Lata Mangeshkar, Sachin Gupta, Shiv-Hari",
    "music_id": "455144, 455109, 461964, 466097",
    "origin": "none",
    "perma_url": "https://www.jiosaavn.com/song/dekha-ek-khwab-lofi/SDcCYy5bUFw",
    "play_count": 232227,
    "primary_artists": "Kishore Kumar, Lata Mangeshkar, Sachin Gupta",
    "primary_artists_id": "455144, 455109, 461964",
    "release_date": "2022-09-15",
    "rights": {
      "cacheable": true,
      "code": 0,
      "delete_cached_object": false,
      "reason": ""
    },
    "singers": "",
    "song": "Dekha Ek Khwab - Lofi",
    "starred": "false",
    "starring": "",
    "triller_available": false,
    "type": "",
    "vcode": "010910081677669",
    "vlink": "https://jiotunepreview.jio.com/content/Converted/010910081634660.mp3",
    "webp": true,
    "year": "2022"
      },
      {
        "320kbps": "true",
    "album": "Attitude Lofi",
    "album_url": "https://www.jiosaavn.com/album/attitude-lofi/kmwwmK0EVLM_",
    "albumid": "51665694",
    "artistMap": {
      "Raj Mawar": "2928718",
      "Sunny Chaudhary": "11384058",
      "Young K": "2159757"
    },
    "cache_state": "false",
    "copyright_text": "© 2024 Sonotek Cassettes Company",
    "duration": "226",
    "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8bbpPgnG452eNjnhFUPSLpDFJ7XZ7cmUusTtxUrRRiH3HXmqP3lBR9492mytrdt3FDnQW0nglPS4=",
    "encrypted_media_path": "NMKyboFo/Fgk2pFXejLHmBxEVk2bqdmDyLd1yGBSKi4IElHWnPtdxV+gcIcfP7B+",
    "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy0EipR/zXI21LGbfmVC1G5Y6f2pSEhsoOgvwVKovQbpCJm+RJ47b5vhw7tS9a8Gtq",
    "explicit_content": 0,
    "featured_artists": "",
    "featured_artists_id": "",
    "has_lyrics": "false",
    "id": "DCcQjPE2",
    "image": "https://c.saavncdn.com/286/Attitude-Lofi-Haryanvi-2024-20240205230006-500x500.jpg",
    "is_dolby_content": false,
    "is_drm": 1,
    "label": "Sonotek Cassettes Company",
    "label_url": "/label/sonotek-cassettes-company-albums/GwHwLdSS6ow_",
    "language": "haryanvi",
    "lyrics_snippet": "",
    "media_preview_url": "https://preview.saavncdn.com/286/366982b56208062b363068898c8d63f1_96_p.mp4",
    "media_url": "https://aac.saavncdn.com/286/366982b56208062b363068898c8d63f1_320.mp4",
    "music": "Young K",
    "music_id": "2159757",
    "origin": "none",
    "perma_url": "https://www.jiosaavn.com/song/attitude-lofi/NCsIYB5gcgE",
    "play_count": 29175,
    "primary_artists": "Raj Mawar",
    "primary_artists_id": "2928718",
    "release_date": "2024-02-05",
    "rights": {
      "cacheable": true,
      "code": 0,
      "delete_cached_object": false,
      "reason": ""
    },
    "singers": "Raj Mawar",
    "song": "Attitude Lofi",
    "starred": "false",
    "starring": "",
    "triller_available": false,
    "type": "",
    "vcode": "010911262338394",
    "vlink": "https://jiotunepreview.jio.com/content/Converted/010911262294728.mp3",
    "webp": true,
    "year": "2024"
      },
      {
        "320kbps": "true",
    "album": "Shape Lofi",
    "album_url": "https://www.jiosaavn.com/album/shape-lofi/fmPEz0ApnCQ_",
    "albumid": "44959912",
    "artistMap": {
      "Kaka": "12040540"
    },
    "cache_state": "false",
    "copyright_text": "℗ 2023 Kaka Ji Records",
    "duration": "255",
    "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8z4+3X49pSVFze9BV28nE8KLFUmLEU+SJ4t+5nTcO3+0IBNypJZCuNY92mytrdt3FDnQW0nglPS4=",
    "encrypted_media_path": "NMKyboFo/FjFv5yn520RfgVQSJEZLDisDw14NvmlvVqAqjMdAlzI/dNlxF8NrN0Z",
    "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy7y2A8BfVIabl4FktYDnxCXLK3asrJItnSN9GTDdDT3NsiwkyDilalxw7tS9a8Gtq",
    "explicit_content": 0,
    "featured_artists": "",
    "featured_artists_id": "",
    "has_lyrics": "false",
    "id": "xtuj2zY6",
    "image": "https://c.saavncdn.com/333/Shape-Lofi-Punjabi-2023-20230427235804-500x500.jpg",
    "is_dolby_content": false,
    "is_drm": 1,
    "label": "Sky Digital",
    "label_url": "/label/sky-digital-albums/2qRD0FfZqfU_",
    "language": "punjabi",
    "lyrics_snippet": "",
    "media_preview_url": "https://preview.saavncdn.com/333/99f10cbe3b0362336fb08c429e591cef_96_p.mp4",
    "media_url": "https://aac.saavncdn.com/333/99f10cbe3b0362336fb08c429e591cef_320.mp4",
    "music": "Kaka",
    "music_id": "12040540",
    "origin": "none",
    "perma_url": "https://www.jiosaavn.com/song/shape-lofi/CBweW0ZKbgU",
    "play_count": 128457,
    "primary_artists": "Kaka",
    "primary_artists_id": "12040540",
    "release_date": "2023-05-02",
    "rights": {
      "cacheable": true,
      "code": 0,
      "delete_cached_object": false,
      "reason": ""
    },
    "singers": "Kaka",
    "song": "Shape Lofi",
    "starred": "false",
    "starring": "",
    "triller_available": false,
    "type": "",
    "vcode": "010912552039169",
    "vlink": "https://jiotunepreview.jio.com/content/Converted/010912551996236.mp3",
    "webp": true,
    "year": "2023"
      },
      {
        "320kbps": "true",
    "album": "ANYWAY",
    "album_url": "https://www.jiosaavn.com/album/anyway/VstxAw8vrF0_",
    "albumid": "41911181",
    "artistMap": {
      "Cheema Y": "8758099",
      "Gur Sidhu": "2613966"
    },
    "cache_state": "false",
    "copyright_text": "℗ 2023 Brown Town Music",
    "duration": "175",
    "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8LTtG8NQcmI/LwmlUN0I73S/kXzp6tPUTOlIfxim00LBg37XgKWSs+492mytrdt3FDnQW0nglPS4=",
    "encrypted_media_path": "NMKyboFo/FiS3w0KCTB/B8rfeFUbmovJgCy0FRcZZsZoWeJci3YLd211UHUkOrSH",
    "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyIB2YTIlXvQd/KwBOcTS/rlaA9B4/4w2UIVYsFhWQXcBCOxaSPZjz5Rw7tS9a8Gtq",
    "explicit_content": 1,
    "featured_artists": "",
    "featured_artists_id": "",
    "has_lyrics": "true",
    "id": "zMKc8TDs",
    "image": "https://c.saavncdn.com/647/ANYWAY-Punjabi-2023-20230123135558-500x500.jpg",
    "is_dolby_content": false,
    "is_drm": 1,
    "label": "Brown Town Music",
    "label_url": "/label/brown-town-music-albums/c4E16ftFpro_",
    "language": "punjabi",
    "lyrics_snippet": "ਲੋਕੀਂ ਤਾਂ ਮੰਗਾਉਂਦੇ ਅਫ਼ਗ਼ਾਨ ਤੋਂ ਅਫ਼ੀਮ",
    "media_preview_url": "https://preview.saavncdn.com/647/58ba64a379844f76133420831e34b5a0_96_p.mp4",
    "media_url": "https://aac.saavncdn.com/647/58ba64a379844f76133420831e34b5a0_320.mp4",
    "music": "Gur Sidhu",
    "music_id": "2613966",
    "origin": "none",
    "perma_url": "https://www.jiosaavn.com/song/california-love/CiUgUkxkc0A",
    "play_count": 20729003,
    "primary_artists": "Cheema Y, Gur Sidhu",
    "primary_artists_id": "8758099, 2613966",
    "release_date": "2023-01-30",
    "rights": {
      "cacheable": true,
      "code": 0,
      "delete_cached_object": false,
      "reason": ""
    },
    "singers": "Cheema Y, Gur Sidhu",
    "song": "California Love",
    "starred": "false",
    "starring": "",
    "triller_available": false,
    "type": "",
    "vcode": "010912261998205",
    "vlink": "https://jiotunepreview.jio.com/content/Converted/010912261957404.mp3",
    "webp": true,
    "year": "2023"
      },
      {
        "320kbps": "true",
    "album": "Jale 2 Lofi",
    "album_url": "https://www.jiosaavn.com/album/jale-2-lofi/ZerNkmp1rug_",
    "albumid": "50866778",
    "artistMap": {
      "Aman Jaji": "5708766",
      "Sapna Choudhary": "5007756",
      "Shiva Choudhary": "7803820"
    },
    "cache_state": "false",
    "copyright_text": "℗ 2024 2024 Desi Geet",
    "duration": "181",
    "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8j9vWVFEUQthpj7Ex6QDK0Tm19fOBnlHwP9ZKWsBrNGwZarwQLwKJ7o92mytrdt3FDnQW0nglPS4=",
    "encrypted_media_path": "NMKyboFo/FiBC7X1TuoOpYCodM/lHTywqQwvNQbqUww2wIgI2Duz+nZ5dYZN4skW",
    "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDygypsSeahO3mnxawciQsyHBjDMMCBNXqgO9AgBbAbCxpOJ8vteUBOyRw7tS9a8Gtq",
    "explicit_content": 0,
    "featured_artists": "",
    "featured_artists_id": "",
    "has_lyrics": "false",
    "id": "gTqkQGIW",
    "image": "https://c.saavncdn.com/078/Jale-2-Lofi-Haryanvi-2024-20240418194715-500x500.jpg",
    "is_dolby_content": false,
    "is_drm": 1,
    "label": "Desi Geet",
    "label_url": "/label/desi-geet-albums/ft04abujtMw_",
    "language": "haryanvi",
    "lyrics_snippet": "",
    "media_preview_url": "https://preview.saavncdn.com/078/f1319176911988c4dccea0a7e652f6ed_96_p.mp4",
    "media_url": "https://aac.saavncdn.com/078/f1319176911988c4dccea0a7e652f6ed_320.mp4",
    "music": "Aman Jaji",
    "music_id": "5708766",
    "origin": "none",
    "perma_url": "https://www.jiosaavn.com/song/jale-2-lofi/FzwaWiV3fmQ",
    "play_count": 295387,
    "primary_artists": "Shiva Choudhary, Sapna Choudhary",
    "primary_artists_id": "7803820, 5007756",
    "release_date": "2024-01-03",
    "rights": {
      "cacheable": true,
      "code": 0,
      "delete_cached_object": false,
      "reason": ""
    },
    "singers": "Shiva Choudhary, Sapna Choudhary",
    "song": "Jale 2 Lofi",
    "starred": "false",
    "starring": "",
    "triller_available": false,
    "type": "",
    "vcode": "010912552204830",
    "vlink": "https://jiotunepreview.jio.com/content/Converted/010912552158182.mp3",
    "webp": true,
    "year": "2024"
      },
    {
        "320kbps": "true",
        "album": "Lo[ve]fi",
        "album_url": "https://www.jiosaavn.com/album/lovefi/E7J5s-CmGBQ_",
        "albumid": "28458987",
        "artistMap": {
            "Akshita": "1250784",
            "Akshita Singh": "11025734",
            "Luz Vandyke": "11025733",
            "Mary Herrington": "11025732"
        },
        "cache_state": "false",
        "copyright_text": "© 2021 Akshita",
        "duration": "236",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD8MxBexDbfVvQshLrDpaweq0F1GNzXWo6rmkWZoJqHIr/j6lhElrPnBY92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FhwDgYCvfv26+YxqxRgIRP4+MU0wCA4AVCsO+pLa5F8WK/AaUU1nY+S",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyIYCOf52D25Ew+2XgFZk0v9hvDtilRQ5kw7/4jWgmAbrpiLTSRMsYPBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "5GZeEWwU",
        "image": "https://c.saavncdn.com/478/Lo-ve-fi-Hindi-2021-20210716010150-500x500.jpg",
        "is_dolby_content": false,
        "label": "Akshita",
        "label_url": "/label/akshita-albums/BC329HSQHvM_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/478/7d2175551e7512f7f63bf6b967428161_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/478/7d2175551e7512f7f63bf6b967428161_320.mp4",
        "music": "Akshita Singh",
        "music_id": "11025734",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/lovefi/RS8xVDFnQGY",
        "play_count": 63236,
        "primary_artists": "Akshita",
        "primary_artists_id": "1250784",
        "release_date": "2021-01-01",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Akshita",
        "song": "Lo[ve]fi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2021"
    },
    {
        "320kbps": "true",
        "album": "Sunderkand-Lofi",
        "album_url": "https://www.jiosaavn.com/album/sunderkand-lofi/KM3RUq9AL4k_",
        "albumid": "45092758",
        "artistMap": {
            "Baljeet Singh Chahal": "10146860",
            "Rasraj Ji Maharaj": "12694826",
            "Traditional": "455090"
        },
        "cache_state": "false",
        "copyright_text": "© 2023 Shubham Audio Video",
        "duration": "3788",
        "encrypted_drm_media_url": "ID2ieOjCrwdjlkMElYlzWCptgNdUpWD81TehDXUV0Y8R74CST5x3UEYYcUJ0bcUiqcaEKUAMLyatclj3yC2Muo92mytrdt3FDnQW0nglPS4=",
        "encrypted_media_path": "NMKyboFo/FifDV18LSKNHzqPMhLfcv1wMuIG/PMr6Az2o/RA5ekcMsfXliLjMvRU",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyHdooK9JOGlF+m913JQ+uw9VsyitIXOJwyRLE+51wpP6Ar/kv7/wvDRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "VkSwM38Q",
        "image": "https://c.saavncdn.com/612/Sunderkand-Lofi-Hindi-2023-20230502210050-500x500.jpg",
        "is_dolby_content": false,
        "label": "Shubham Audio Video",
        "label_url": "/label/shubham-audio-video-albums/g4kx7KY1Hxw_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/612/d63684d7734497a308420cd65cf33a6c_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/612/d63684d7734497a308420cd65cf33a6c_320.mp4",
        "music": "Baljeet Singh Chahal",
        "music_id": "10146860",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/sunderkand-lofi/JgM4RjkDD2I",
        "play_count": 43734,
        "primary_artists": "Rasraj Ji Maharaj",
        "primary_artists_id": "12694826",
        "release_date": "2023-05-02",
        "rights": {
            "cacheable": true,
            "code": 0,
            "delete_cached_object": false,
            "reason": ""
        },
        "singers": "Rasraj Ji Maharaj",
        "song": "Sunderkand-Lofi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010912461583929",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010912461540046.mp3",
        "webp": true,
        "year": "2023"
    }
]